#!/bin/bash

# Convenience script to plot GSA data.  This script assumes that the
# GSA data has already been generated by submitting jobs via the
# submit_gsa_jobs.sh script.  This script assumes that the jobs have
# successfully completed.

TMP_DIR="tmp/"
mkdir -p "$TMP_DIR"

# Ensure at least one input .csv file has been specified
if [ $# -lt 1 ]; then
    echo "Specify input CSV files to be aggregated and analyzed."
    exit 2
fi

# File name for the full data file
FULL_DATA="${TMP_DIR}/full_gsa.csv"
rm -f "${FULL_DATA}"
# Aggregate all the GSA data into a single file in TMP dir
echo "Aggregating files: $* ..."
for dataFile in $*
do
    grep -v "\-\-" "$dataFile" >> "$FULL_DATA"
done

# Compile all the necessary support C++ program
g++ -g -Wall -std=c++11 -O3 gsa.cpp -o gsa
g++ -g -Wall -std=c++11 -O3 round_tics.cpp -o round_tics

# Now plot the 2 PDF charts on the full data file.
echo "Generating and plotting GSA curves (takes ~1 minute!)..."
gnuplot -e "dir=\"${TMP_DIR}\"" -e "csv=\"full_gsa\"" plot_gsa.gnu

# Now plot the overall analysis chart
echo "Plotting aggregate GSA analysis chart (takes few seconds only)..."
SUFFIX="${TMP_DIR}/full_gsa"
gnuplot -e "suffix=\"${SUFFIX}\"" plot_gsa_anal.gnu

# End of script.
