/* 
 * File:   PHOLDAgent.h
 * Author: Meseret Gebre
 *
 * Created on January 15, 2009, 11:04 PM
 */

#ifndef _PHOLDAgent_H
#define	_PHOLDAgent_H

#include "Agent.h"
#include "PholdState.h"

class PHOLDAgent : public muse::Agent {

public:
    PHOLDAgent(muse::AgentID , PholdState *,int x, int y, int n, int d,
               int lookAhead = 1, double selfEvents = 0.0,
               size_t granularity = 0);

    void initialize() throw (std::exception);

    void executeTask(const muse::EventContainer* events);

    void finalize();

protected:
    /** Simulate some granularity (i.e., CPU usage) for the event.

        This method merely runs a loop generating random numbers to
        simulate some processing done for each event.  Currently, the
        granularity is a fixed value, set when an agent is created.

    */
    void simGranularity();
    
private:
    int X,Y,N,Delay;

    /** Fixed lookahead virtual time delay for generating events.
        
        The virtual time events generated by this agent have this
        fixed look ahead virtual time value added to them.
    */
    int lookAhead;

    /** Fraction of events that the agent should schedule to itself.

        This value indicates the probability that this agent should
        schedule events to itself.  This value is in the range 0.0 to
        0.99 and is used with the boolean expression ((rand() % 1000)
        / 1000.0) < selfEvents.  If the boolean expression returns
        true, then this agent schedule events to itself.  Note that at
        a given virtual time, the maximum number of self-events is
        limited by events * N.
    */
    double selfEvents;
    
    /** The random seed value that is used to generate random delays.

        Each agent uses a custom random seed to ensure that the events
        generated by it have some degree of repeatability between
        runs. Otherwise the types of events generated between runs
        will be vastly different impacting results of tests.  In most
        cases it would be best to set the \c --delay parameter to 0 to
        ensure repeatable results.
    */
    unsigned int seed;

    /** A user-specified granularity -- that is, the number of loops
        to run for each event to add some load/granularity for each
        event.

        This instance variable is set to indicate the number of loops
        or iterations that must be executed by the agent to simulate
        some granularity, i.e., CPU used per event.
    */
    size_t granularity;
};

#endif	/* _PHOLDAgent_H */
